version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: ng1
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backendnet

  nodeapp1:
    image: nodeapp
    container_name: nodeapp1
    hostname: nodeapp1
    networks:
      - backendnet

  nodeapp2:
    image: nodeapp
    container_name: nodeapp2
    hostname: nodeapp2
    networks:
      - backendnet

  nodeapp3:
    image: nodeapp
    container_name: nodeapp3
    hostname: nodeapp3
    networks:
      - backendnet

networks:
  backendnet:
    driver: bridge
